# database.yml

production:
  host: localhost
  schema_name: alphabeta
  username: root
  password: "factor-rocks"

development:
  host: localhost
  schema_name: alphabeta
  username: root
  password: "factor-rocks"
