# Factor Configuration for Vietnam Factor Investing Platform
# Version: 1.0
# Last Updated: 2025-05-27
# 
# This configuration defines metadata for all factors including:
# - Category (quality, value, momentum, risk)
# - Sign (1 = higher is better, -1 = lower is better)
# - Optimal lag (days) for forward return prediction
# - Winsorization limits [lower, upper] as percentiles
# - Minimum history requirements
# - Validation thresholds

# Banking Sector Factors
banking:
  # Core Financial Metrics
  NII:
    category: scale
    sign: 1
    optimal_lag: 63
    winsorize: [0.01, 0.99]
    min_history_quarters: 4
    description: "Net Interest Income (Billions VND)"
    
  Net_Fee_Income:
    category: scale
    sign: 1
    optimal_lag: 63
    winsorize: [0.01, 0.99]
    min_history_quarters: 4
    description: "Net Fee Income (Billions VND)"
    
  TOI:
    category: scale
    sign: 1
    optimal_lag: 63
    winsorize: [0.01, 0.99]
    min_history_quarters: 4
    description: "Total Operating Income (Billions VND)"
    
  Operating_Profit:
    category: scale
    sign: 1
    optimal_lag: 63
    winsorize: [0.01, 0.99]
    min_history_quarters: 4
    description: "Operating Profit (Billions VND)"
    
  Net_Profit:
    category: scale
    sign: 1
    optimal_lag: 63
    winsorize: [0.01, 0.99]
    min_history_quarters: 4
    description: "Net Profit (Billions VND)"
    
  # Profitability Ratios
  ROAE:
    category: quality
    sign: 1
    optimal_lag: 63
    winsorize: [0.02, 0.98]
    min_history_quarters: 8
    validation_range: [5, 30]  # Expected range 5-30%
    description: "Return on Average Equity (%)"
    
  ROAA:
    category: quality
    sign: 1
    optimal_lag: 63
    winsorize: [0.02, 0.98]
    min_history_quarters: 8
    validation_range: [0.5, 3.0]  # Expected range 0.5-3.0%
    description: "Return on Average Assets (%)"
    
  NIM:
    category: quality
    sign: 1
    optimal_lag: 63
    winsorize: [0.02, 0.98]
    min_history_quarters: 4
    validation_range: [2.0, 6.0]  # Expected range 2-6%
    description: "Net Interest Margin (%)"
    
  # Efficiency Ratios
  CIR:
    category: quality
    sign: -1  # Lower is better
    optimal_lag: 63
    winsorize: [0.02, 0.98]
    min_history_quarters: 4
    validation_range: [25, 60]  # Expected range 25-60%
    description: "Cost-to-Income Ratio (%)"
    
  # Risk Ratios
  LDR:
    category: risk
    sign: -1  # Lower is better (liquidity perspective)
    optimal_lag: 63
    winsorize: [0.05, 0.95]
    min_history_quarters: 4
    validation_range: [60, 95]  # Expected range 60-95%
    description: "Loan-to-Deposit Ratio (%)"
    
  Cost_of_Credit:
    category: risk
    sign: -1  # Lower is better
    optimal_lag: 63
    winsorize: [0.01, 0.99]
    min_history_quarters: 4
    validation_range: [0.2, 3.0]  # Expected range 0.2-3.0%
    description: "Cost of Credit (annualized %)"
    
  LLR_Ratio:
    category: risk
    sign: 1  # Higher is better (more conservative)
    optimal_lag: 63
    winsorize: [0.02, 0.98]
    min_history_quarters: 4
    validation_range: [0.5, 3.0]  # Expected range 0.5-3.0%
    description: "Loan Loss Reserve Ratio (%)"
    
  CAR_Proxy:
    category: risk
    sign: 1  # Higher is better
    optimal_lag: 63
    winsorize: [0.05, 0.95]
    min_history_quarters: 4
    validation_range: [8, 20]  # Expected range 8-20%
    description: "Capital Adequacy Ratio Proxy (%)"
    
  AccrualsRatio:
    category: quality
    sign: -1  # Lower is better (higher earnings quality)
    optimal_lag: 63
    winsorize: [0.01, 0.99]
    min_history_quarters: 8
    validation_range: [-1.0, 1.0]  # Expected range -1% to 1%
    description: "Accruals Ratio (Net Profit - CFO) / Avg Assets"
    
  # Growth Metrics (YoY)
  NII_YoY:
    category: momentum
    sign: 1
    optimal_lag: 63
    winsorize: [0.02, 0.98]
    min_history_quarters: 8
    validation_range: [-20, 50]  # Expected range -20% to 50%
    description: "Net Interest Income Year-over-Year Growth (%)"
    
  Net_Profit_YoY:
    category: momentum
    sign: 1
    optimal_lag: 63
    winsorize: [0.02, 0.98]
    min_history_quarters: 8
    validation_range: [-30, 60]  # Expected range -30% to 60%
    description: "Net Profit Year-over-Year Growth (%)"
    
  Total_Assets_YoY:
    category: momentum
    sign: 1
    optimal_lag: 63
    winsorize: [0.05, 0.95]
    min_history_quarters: 8
    validation_range: [0, 30]  # Expected range 0-30%
    description: "Total Assets Year-over-Year Growth (%)"
    
  Gross_Loans_YoY:
    category: momentum
    sign: 1
    optimal_lag: 63
    winsorize: [0.05, 0.95]
    min_history_quarters: 8
    validation_range: [0, 35]  # Expected range 0-35%
    description: "Gross Loans Year-over-Year Growth (%)"
    
  # TTM Growth Metrics
  NII_TTM_YoY:
    category: momentum
    sign: 1
    optimal_lag: 63
    winsorize: [0.02, 0.98]
    min_history_quarters: 12
    validation_range: [-10, 40]  # Expected range -10% to 40%
    description: "NII Trailing Twelve Months YoY Growth (%)"
    
  Net_Profit_TTM_YoY:
    category: momentum
    sign: 1
    optimal_lag: 63
    winsorize: [0.02, 0.98]
    min_history_quarters: 12
    validation_range: [-20, 50]  # Expected range -20% to 50%
    description: "Net Profit TTM YoY Growth (%)"
    
  # Multi-Year CAGR
  Net_Profit_3Y_CAGR:
    category: momentum
    sign: 1
    optimal_lag: 63
    winsorize: [0.02, 0.98]
    min_history_quarters: 16
    validation_range: [-10, 40]  # Expected range -10% to 40%
    description: "Net Profit 3-Year CAGR (%)"
    
  Net_Profit_5Y_CAGR:
    category: momentum
    sign: 1
    optimal_lag: 63
    winsorize: [0.02, 0.98]
    min_history_quarters: 24
    validation_range: [-5, 35]  # Expected range -5% to 35%
    description: "Net Profit 5-Year CAGR (%)"

# Non-Financial Sector Factors
non_financial:
  # Profitability Metrics
  GrossProfitMargin:
    category: quality
    sign: 1
    optimal_lag: 63
    winsorize: [0.02, 0.98]
    min_history_quarters: 4
    validation_range: [5, 60]  # Expected range 5-60%
    description: "Gross Profit Margin (%)"
    
  EBITMargin:
    category: quality
    sign: 1
    optimal_lag: 63
    winsorize: [0.01, 0.99]
    min_history_quarters: 4
    validation_range: [-10, 40]  # Can be negative
    description: "EBIT Margin (%)"
    
  NetProfitMargin:
    category: quality
    sign: 1
    optimal_lag: 63
    winsorize: [0.01, 0.99]
    min_history_quarters: 4
    validation_range: [-20, 30]  # Can be negative
    description: "Net Profit Margin (%)"
    
  ROIC:
    category: quality
    sign: 1
    optimal_lag: 63
    winsorize: [0.01, 0.99]
    min_history_quarters: 8
    validation_range: [-20, 50]  # Can be negative
    description: "Return on Invested Capital (%)"
    
  # Efficiency Metrics
  DSO:
    category: quality
    sign: -1  # Lower is better
    optimal_lag: 63
    winsorize: [0.02, 0.98]
    min_history_quarters: 4
    validation_range: [0, 180]  # Expected 0-180 days
    description: "Days Sales Outstanding"
    
  DIO:
    category: quality
    sign: -1  # Lower is better
    optimal_lag: 63
    winsorize: [0.02, 0.98]
    min_history_quarters: 4
    validation_range: [0, 365]  # Expected 0-365 days
    description: "Days Inventory Outstanding"
    
  DPO:
    category: quality
    sign: 1  # Higher is better (longer payment terms)
    optimal_lag: 63
    winsorize: [0.02, 0.98]
    min_history_quarters: 4
    validation_range: [0, 180]  # Expected 0-180 days
    description: "Days Payables Outstanding"
    
  CCC:
    category: quality
    sign: -1  # Lower is better
    optimal_lag: 63
    winsorize: [0.01, 0.99]
    min_history_quarters: 4
    validation_range: [-60, 300]  # Can be negative (good)
    description: "Cash Conversion Cycle"
    
  # Leverage Metrics
  NetDebtToEBITDA:
    category: risk
    sign: -1  # Lower is better
    optimal_lag: 63
    winsorize: [0.01, 0.99]
    min_history_quarters: 8
    validation_range: [-2, 10]  # Can be negative (net cash)
    description: "Net Debt to EBITDA Ratio"
    
  InterestCoverage:
    category: quality
    sign: 1  # Higher is better
    optimal_lag: 63
    winsorize: [0.01, 0.99]
    min_history_quarters: 4
    validation_range: [0, 50]  # Expected 0-50x
    description: "Interest Coverage Ratio (EBIT/Interest)"
    
  # Growth Metrics
  NetRevenue_YoY:
    category: momentum
    sign: 1
    optimal_lag: 63
    winsorize: [0.02, 0.98]
    min_history_quarters: 8
    validation_range: [-30, 100]  # Expected -30% to 100%
    description: "Net Revenue Year-over-Year Growth (%)"
    
  EBITDA_YoY:
    category: momentum
    sign: 1
    optimal_lag: 63
    winsorize: [0.01, 0.99]
    min_history_quarters: 8
    validation_range: [-50, 150]  # Higher volatility than revenue
    description: "EBITDA Year-over-Year Growth (%)"
    
  NetProfitParent_YoY:
    category: momentum
    sign: 1
    optimal_lag: 63
    winsorize: [0.01, 0.99]
    min_history_quarters: 8
    validation_range: [-100, 200]  # Can be very volatile
    description: "Net Profit Parent Year-over-Year Growth (%)"

# Real Estate Sector Factors  
real_estate:
  # Real Estate Specific Metrics
  RevPerSqm:
    category: quality
    sign: 1
    optimal_lag: 63
    winsorize: [0.02, 0.98]
    min_history_quarters: 4
    validation_range: [0, 100]  # Million VND per sqm
    description: "Revenue per Square Meter (Million VND)"
    
  InventoryTurnover:
    category: quality
    sign: 1  # Higher is better
    optimal_lag: 63
    winsorize: [0.02, 0.98]
    min_history_quarters: 4
    validation_range: [0, 5]  # Expected 0-5x per year
    description: "Inventory Turnover Ratio"
    
  # Common metrics shared with non-financial
  ROIC:
    category: quality
    sign: 1
    optimal_lag: 63
    winsorize: [0.01, 0.99]
    min_history_quarters: 8
    validation_range: [-10, 30]
    description: "Return on Invested Capital (%)"

# Insurance Sector Factors
insurance:
  # Insurance Specific Metrics
  CombinedRatio:
    category: quality
    sign: -1  # Lower is better
    optimal_lag: 63
    winsorize: [0.02, 0.98]
    min_history_quarters: 4
    validation_range: [70, 120]  # Expected 70-120%
    description: "Combined Ratio (Loss + Expense) %"
    
  LossRatio:
    category: quality
    sign: -1  # Lower is better
    optimal_lag: 63
    winsorize: [0.02, 0.98]
    min_history_quarters: 4
    validation_range: [40, 90]  # Expected 40-90%
    description: "Loss Ratio %"
    
  InvestmentYield:
    category: quality
    sign: 1
    optimal_lag: 63
    winsorize: [0.02, 0.98]
    min_history_quarters: 4
    validation_range: [2, 10]  # Expected 2-10%
    description: "Investment Yield %"

# Securities Sector Factors
securities:
  # Securities Specific Metrics
  BrokerageMargin:
    category: quality
    sign: 1
    optimal_lag: 63
    winsorize: [0.02, 0.98]
    min_history_quarters: 4
    validation_range: [20, 80]  # Expected 20-80%
    description: "Brokerage Revenue Margin %"
    
  MarginLendingRatio:
    category: risk
    sign: -1  # Lower is better (risk perspective)
    optimal_lag: 63
    winsorize: [0.02, 0.98]
    min_history_quarters: 4
    validation_range: [0, 60]  # Expected 0-60%
    description: "Margin Lending to Equity %"

# Global Configuration
global:
  # Cross-sectional validation thresholds
  zscore_threshold: 3.0  # Flag factors beyond 3 standard deviations
  
  # Time-series validation thresholds  
  qoq_change_threshold: 0.5  # Flag 50%+ quarter-over-quarter changes
  yoy_change_threshold: 2.0  # Flag 200%+ year-over-year changes
  
  # Data quality thresholds
  min_coverage_ratio: 0.7  # Require 70%+ data coverage for factor calculation
  max_missing_quarters: 2  # Maximum consecutive missing quarters allowed
  
  # Factor calculation parameters
  ttm_quarters: 4  # Quarters for TTM calculation
  cagr_3y_quarters: 12  # Quarters for 3-year CAGR
  cagr_5y_quarters: 20  # Quarters for 5-year CAGR
  
  # Backtesting parameters
  default_rebalance_frequency: "quarterly"
  default_holding_period: 63  # Trading days
  transaction_cost_bps: 10  # Basis points one-way
  market_impact_bps: 2  # Basis points slippage